### ISSUE TITLE
Cloudflareにデプロイすると「Error 1101 Worker threw exception」とエラーが表示される

### ISSUE THREAD

**Issue by anno12345** [edginer/eddiner#15]
**バグの概要**
Cloudflareにプロジェクトをデプロイすると「Error 1101 Worker threw exception」とエラーが表示されます

**再現方法**
1. `README.md`のインストール方法の手順に従って、1から手順を実行しました
2. 手順2は該当のファイル(`/src/schema.sql`)がなかったため、下記のようにコマンドを読み替えました
3. デプロイしたページのTOPページを閲覧するとCloudflareから`Error 1101 Worker threw exception`と表示されます

```zsh
$ npx wrangler d1 execute zerochedge-d1 --file=./migrations/initial.sql
$ npx wrangler d1 execute zerochedge-d1 --file=./migrations/threads/add-attributes-into-threads_2023-12-24/up.sql
$ npx wrangler deploy
```

**本来あるべき振る舞い**
TOPページが表示される

**スクリーンショット**
<img width="340" alt="スクリーンショット 2024-03-26 15 43 06" src="https://github.com/edginer/eddiner/assets/165003014/717c7bc1-29fa-47d7-a08a-ec8f0ac6bf4d">

**実行環境**
以下を参考に埋めてください
 - OS: macOS 14.4
 - Browser Google Chrome
 - Browser Version 123.0.6312.59
 - Node.js 20.11.1
 
```zsh
$ cargo --version
cargo 1.77.0 (3fe68eabf 2024-02-29)

$ rustc --version
rustc 1.77.0 (aedd173a2 2024-03-17)

$ rustdoc --version
rustdoc 1.77.0 (aedd173a2 2024-03-17)
```

**その他**
`wrangler`は最新版に更新済み(`package.json`記載の`2.13.0`だと`npx wrangler deploy`が動かないため)

`wrangler dev`でローカル環境でコマンドを実行すると下記のエラーが表示されます(本番でも`The script will never generate a response.`がダッシュボードのログに記録されているため、ローカル環境で発生しているものと同一のエラーと思われます)
```
Error: The script will never generate a response.
    at async Object.fetch (file:///Users/hogehoge/eddiner/node_modules/miniflare/dist/src/workers/core/entry.worker.js:895:22)
```

**Comment by anno12345** [comment]
こちら自己解決しました。
`wrangler.toml.sample`に下記の記述が抜けていたようです(データベース名は適当に設定)

```toml
[[d1_databases]]
binding = "DB_THREADS"
database_name = "zerochedge-threads"
database_id = "<fill-your-d1-database-id>"

[[d1_databases]]
binding = "DB_RESPONSES"
database_name = "zerochedge-db-response"
database_id = "<fill-your-d1-database-id>"

[[d1_databases]]
binding = "DB_RESPONSES_2"
database_name = "zerochedge-db-response2"
database_id = "<fill-your-d1-database-id>"

[[d1_databases]]
binding = "DB_RESPONSES_3"
database_name = "zerochedge-db-response3"
database_id = "<fill-your-d1-database-id>"
```
